---
# GitHub Provider
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-upjet-github
spec:
  package: ghcr.io/crossplane-contrib/provider-upjet-github:v0.19-provider-cache-testing-a3b6345
