{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubecore-ci-workflows.fullname" . }}-secret-reader
  namespace: {{ include "kubecore-ci-workflows.namespace" . }}
  labels:
    {{- include "kubecore-ci-workflows.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubecore-ci-workflows.fullname" . }}-secret-reader
  namespace: {{ include "kubecore-ci-workflows.namespace" . }}
  labels:
    {{- include "kubecore-ci-workflows.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubecore-ci-workflows.fullname" . }}-secret-reader
subjects:
- kind: ServiceAccount
  name: {{ include "kubecore-ci-workflows.serviceAccountName" . }}
  namespace: {{ include "kubecore-ci-workflows.namespace" . }}
{{- end }}
