apiVersion: v2
name: kubecore-ci-workflows
description: Argo Workflows CI pipeline templates for KubeCore platform
type: application
version: 0.12.84
appVersion: "0.9.9"
maintainers:
  - name: Novelcore Platform Team
    email: platform@novelcore.io
keywords:
  - ci-cd
  - argo-workflows
  - buildkit
  - kubecore
home: https://github.com/novelcore/charts
sources:
  - https://github.com/novelcore/charts
kubeVersion: ">=1.26.0-0"
