apiVersion: v2
appVersion: 2.6.0
description: A Helm chart to deploy the Percona Operator for PostgreSQL
home: https://docs.percona.com/percona-operator-for-postgresql/2.0/
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
maintainers:
  - email: sergey.pronin@percona.com
    name: spron-in
  - email: natalia.marukovich@gmail.com
    name: nmarukovich
  - email: julio.pasinatto@percona.com
    name: jvpasinatto
name: pg-operator
type: application
version: 2.6.0
syncMetadata:
  source: percona/pg-operator
  syncedAt: "2025-08-05T09:45:21Z"
  syncedVersion: 2.6.0
