{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubecore-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - environmentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - environmentconfigs/status
  verbs:
  - get
- apiGroups:
  - aws.provider.platform.kubecore.io
  resources:
  - xawsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.provider.platform.kubecore.io
  resources:
  - xawsproviders/status
  verbs:
  - get
- apiGroups:
  - aws.upbound.io
  resources:
  - providerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ec2.aws.upbound.io
  resources:
  - natgateways
  - subnets
  - vpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2.aws.upbound.io
  resources:
  - subnets/status
  - vpcs/status
  verbs:
  - get
- apiGroups:
  - eks.aws.crossplane.io
  resources:
  - xeks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.aws.crossplane.io
  resources:
  - xeks/status
  verbs:
  - get
- apiGroups:
  - eks.aws.upbound.io
  resources:
  - clusterauths
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.aws.upbound.io
  resources:
  - nodegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eks.aws.upbound.io
  resources:
  - nodegroups/status
  verbs:
  - get
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - pushsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.platform.kubecore.io
  resources:
  - xgithubapps
  - xgithubprojects
  - xgithubproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.platform.kubecore.io
  resources:
  - xgithubprojects/status
  - xgithubproviders/status
  verbs:
  - get
- apiGroups:
  - helm.crossplane.io
  resources:
  - providerconfigs
  - releases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.aws.upbound.io
  resources:
  - policies
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - iam.aws.upbound.io
  resources:
  - roles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.aws.upbound.io
  resources:
  - roles/status
  verbs:
  - get
- apiGroups:
  - k8s.platform.kubecore.io
  resources:
  - xk8sapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - objects
  - providerconfigs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - providerconfigs/status
  verbs:
  - get
- apiGroups:
  - platform.kubecore.io
  resources:
  - xawsnetworks
  - xclusteroperators
  - xeks
  - xkubenvs
  - xkubesystems
  - xmlsystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubecore.io
  resources:
  - xawsnetworks/status
  - xawsproviders/status
  - xeks/status
  - xkubenvs/status
  - xkubesystems/status
  verbs:
  - get
- apiGroups:
  - platform.kubecore.io
  resources:
  - xawsproviders
  - xkubeapptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - protection.crossplane.io
  resources:
  - clusterusages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.aws.upbound.io
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps
  - kubeorgs
  - kubepools
  - kubeprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps/finalizers
  - kubeorgs/finalizers
  - kubepools/finalizers
  - kubeprojects/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps/status
  - kubeorgs/status
  - kubepools/status
  - kubeprojects/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
