{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubecore-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - environmentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - environmentconfigs/status
  verbs:
  - get
- apiGroups:
  - authorization.azure.m.upbound.io
  resources:
  - roleassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.m.upbound.io
  - gcp.m.upbound.io
  - helm.m.crossplane.io
  - kubernetes.m.crossplane.io
  resources:
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.provider.platform.kubecore.io
  resources:
  - xawsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.provider.platform.kubecore.io
  resources:
  - xawsproviders/status
  verbs:
  - get
- apiGroups:
  - azure.m.upbound.io
  resources:
  - providerconfigs
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.provider.platform.kubecore.io
  resources:
  - xazureproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.provider.platform.kubecore.io
  resources:
  - xazureproviders/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cloudplatform.gcp.m.upbound.io
  resources:
  - projectiammembers
  - serviceaccountiammembers
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - compute.gcp.m.upbound.io
  resources:
  - firewalls
  - networks
  - routernats
  - routers
  - subnetworks
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - container.gcp.m.upbound.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.gcp.m.upbound.io
  resources:
  - managedzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2.aws.m.upbound.io
  resources:
  - eips
  - internetgateways
  - natgateways
  - routes
  - routetableassociations
  - routetables
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ec2.aws.m.upbound.io
  resources:
  - subnets
  - vpcs
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ec2.aws.m.upbound.io
  resources:
  - subnets/status
  - vpcs/status
  verbs:
  - get
- apiGroups:
  - eks.aws.m.upbound.io
  resources:
  - clusterauths
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eks.aws.m.upbound.io
  resources:
  - clusters
  - nodegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eks.aws.m.upbound.io
  resources:
  - nodegroups/status
  verbs:
  - get
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  - secretstores
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - pushsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.provider.platform.kubecore.io
  resources:
  - xgcpproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.provider.platform.kubecore.io
  resources:
  - xgcpproviders/status
  verbs:
  - get
- apiGroups:
  - github.platform.kubecore.io
  resources:
  - xgithubapps
  - xgithubprojects
  - xgithubproviders
  - xgithubteams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.platform.kubecore.io
  resources:
  - xgithubprojects/status
  - xgithubproviders/status
  - xgithubteams/status
  verbs:
  - get
- apiGroups:
  - helm.m.crossplane.io
  resources:
  - releases
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.aws.m.upbound.io
  resources:
  - policies
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - iam.aws.m.upbound.io
  resources:
  - roles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.aws.m.upbound.io
  resources:
  - roles/status
  verbs:
  - get
- apiGroups:
  - k8s.platform.kubecore.io
  resources:
  - xk8sapps
  - xk8smlapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyvault.azure.m.upbound.io
  resources:
  - vaults
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - providerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - providerconfigs/status
  verbs:
  - get
- apiGroups:
  - kubernetes.m.crossplane.io
  resources:
  - objects
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managedidentity.azure.m.upbound.io
  resources:
  - federatedidentitycredentials
  - userassignedidentities
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.m.upbound.io
  resources:
  - dnszones
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubecore.io
  resources:
  - xaks
  - xakskubesystems
  - xawsnetworks
  - xazurenetworks
  - xclusteroperators
  - xconnections
  - xeks
  - xekskubesystems
  - xgcpnetworks
  - xgcpobservabilitycosts
  - xgkekubesystems
  - xgkes
  - xinterconnects
  - xkubenvs
  - xkubesystems
  - xmlsystems
  - xnetworkmeshes
  - xobservabilities
  - xprojectenvmlstacks
  - xprojectmlstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubecore.io
  resources:
  - xakskubesystems/status
  - xawsnetworks/status
  - xawsproviders/status
  - xazurenetworks/status
  - xconnections/status
  - xeks/status
  - xekskubesystems/status
  - xgcpnetworks/status
  - xgcpobservabilitycosts/status
  - xgkekubesystems/status
  - xinterconnects/status
  - xkubenvs/status
  - xkubesystems/status
  - xnetworkmeshes/status
  - xobservabilities/status
  - xprojectenvmlstacks/status
  - xprojectmlstacks/status
  verbs:
  - get
- apiGroups:
  - platform.kubecore.io
  resources:
  - xawsproviders
  - xkubeapptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - protection.crossplane.io
  resources:
  - clusterusages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - admin
  - cluster-admin
  - edit
  - view
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo.github.upbound.io
  resources:
  - repositoryfiles
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - route53.aws.m.upbound.io
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps
  - kubeorgs
  - kubepools
  - kubeprojects
  - kubeteams
  - toolbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps/finalizers
  - kubeorgs/finalizers
  - kubepools/finalizers
  - kubeprojects/finalizers
  - kubeteams/finalizers
  - toolbindings/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubecore.io
  resources:
  - kubeapps/status
  - kubeorgs/status
  - kubepools/status
  - kubeprojects/status
  - kubeteams/status
  - toolbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secretmanager.gcp.m.upbound.io
  resources:
  - secrets
  - secretversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skupper.io
  resources:
  - accessgrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skupper.io
  resources:
  - accessgrants/status
  verbs:
  - get
- apiGroups:
  - team.github.m.upbound.io
  resources:
  - members
  - teammemberships
  - teams
  verbs:
  - get
  - list
  - update
  - watch
{{- end -}}
