apiVersion: v2
appVersion: 0.7.7
description: The Atlas Kubernetes Operator
name: atlas-operator
type: application
version: 0.7.7
syncMetadata:
  source: oci://ghcr.io/ariga/charts/atlas-operator
  syncedAt: "2025-08-04T16:30:00Z"
  syncedVersion: "0.7.7"
