{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.certManager.enable }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kaos-osr-edge-operator.resourceName" (dict "suffix" "serving-cert" "context" $) }}
    {{- end }}
  name: {{ include "kaos-osr-edge-operator.resourceName" (dict "suffix" "mutating-webhook-configuration" "context" $) }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "kaos-osr-edge-operator.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-osr-kaos-kubecore-io-v1alpha1-knowledgesynccontract
  failurePolicy: Fail
  name: mknowledgesynccontract-v1alpha1.kb.io
  rules:
  - apiGroups:
    - osr.kaos.kubecore.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - knowledgesynccontracts
  sideEffects: None
{{- end }}
