apiVersion: v2
appVersion: v5.17.1
description: Helm chart for the Grafana Operator
name: grafana-operator
type: application
version: v5.17.1
syncMetadata:
  source: grafana/grafana-operator
  syncedAt: "2025-08-05T09:25:25Z"
  syncedVersion: 5.17.1
