{{- if .Values.controllerConfiguration.enabled }}
apiVersion: promoter.argoproj.io/v1alpha1
kind: ControllerConfiguration
metadata:
  name: {{ include "gitops-promoter.controllerConfigurationName" . }}
  namespace: {{ include "gitops-promoter.namespace" . }}
  labels:
    {{- include "gitops-promoter.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.controllerConfiguration.argocdCommitStatus }}
  argocdCommitStatus:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.controllerConfiguration.changeTransferPolicy }}
  changeTransferPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.controllerConfiguration.commitStatus }}
  commitStatus:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.controllerConfiguration.promotionStrategy }}
  promotionStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.controllerConfiguration.pullRequest }}
  pullRequest:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
