{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gitops-promoter.namespace" . }}
  labels:
    {{- include "gitops-promoter.labels" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- include "gitops-promoter.annotations" . | nindent 4 }}
    {{- with .Values.namespace.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}